SHELL:=/usr/bin/env bash

LCACHE ?= $(shell readlink -f ~/.cache/python-testing/pypoetry)
PCACHE ?= /home/qs5779/.cache/pypoetry
PROJECT ?= $(shell git rev-parse --show-toplevel)
PROJECT_VERSION ?= $(shell grep ^current_version .bumpversion.cfg | awk '{print $$NF'} | tr '-' '.')
WHEELS ?= /home/jim/kbfs/private/jim5779/wheels

.PHONY: black mypy lint unit package test publish publish-test vars build chlog
vars:
	echo "PROJECT_VERSION: $(PROJECT_VERSION)"
	@echo "PCACHE: $(PCACHE)"
	@echo "LCACHE: $(LCACHE)"

black:
	poetry run isort .
	poetry run black .

mypy: black
	poetry run mypy dynaddrmgr tests/*.py

lint: mypy
	poetry run flake8 .
	poetry run doc8 -q docs

unit:
	poetry run pytest tests

package:
	poetry check
	poetry run pip check
	poetry run safety check --full-report

test: lint package unit

build: test
	poetry build
	cp dist/dynaddrmgr-$(PROJECT_VERSION)-py3-none-any.whl $(WHEELS)
	sync-wheels

publish: build
	poetry publish

publish-test: test build
	poetry publish -r test-pypi

.PHONY: work37 work38 work39 work
work37:
	docker run --rm -it --volume $(PROJECT):/project/ --volume $(LCACHE):$(PCACHE) qs5779/python-testing:ubuntu20.04-3.7.16 /bin/bash

work38:
	docker run --rm -it --volume $(PROJECT):/project/ --volume $(LCACHE):$(PCACHE) qs5779/python-testing:ubuntu20.04-3.8.16 /bin/bash

work39:
	docker run --rm -it --volume $(PROJECT):/project/ --volume $(LCACHE):$(PCACHE) qs5779/python-testing:ubuntu20.04-3.9.14 /bin/bash

work:
	docker run --rm -it --volume $(PROJECT):/project/ --volume $(LCACHE):$(PCACHE) qs5779/python-testing:$(DISTRO)-$(PYVERS) /bin/bash

chlog:
	github_changelog_generator -u wtfo-guru -p dynaddrmgr
	sed -i -e '/^$$/N;/^\n$$/D' ./CHANGELOG.md
	m2r2 --overwrite --anonymous-references CHANGELOG.md
	sed -i '/This Changelog was automatically generated by/d' ./CHANGELOG.rst
	mv -f ./CHANGELOG.rst ./docs/pages/changelog.rst
	poetry run doc8 -q docs

.DEFAULT:
	@cd docs && $(MAKE) $@

