SHELL:=/usr/bin/env bash
PROJECT_VERSION ?= $(shell grep ^current_version .bumpversion.cfg | awk '{print $$NF'} | tr '-' '.')
WHEELS ?= /home/jim/dev/ansible/wtfplaybooks/wheels

.PHONY: black mypy lint unit package test publish publish-test vars build chlog
vars:
	echo "PROJECT_VERSION: $(PROJECT_VERSION)"

black:
	poetry run isort .
	poetry run black .

mypy: black
	poetry run mypy dynaddrmgr tests/*.py

lint: mypy
	poetry run flake8 .
	poetry run doc8 -q docs

unit:
	poetry run pytest tests

package:
	poetry check
	poetry run pip check
	poetry run safety check --full-report

test: lint package unit

build: test
	poetry build
	cp dist/dynaddrmgr-$(PROJECT_VERSION)-py3-none-any.whl $(WHEELS)
	sync-wheels

publish: build
	poetry publish

publish-test: test build
	poetry publish -r test-pypi

chlog:
	github_changelog_generator -u wtfo-guru -p dynaddrmgr
	sed -i -e '/^$$/N;/^\n$$/D' ./CHANGELOG.md
	m2r2 --overwrite --anonymous-references CHANGELOG.md
	sed -i '/This Changelog was automatically generated by/d' ./CHANGELOG.rst
	mv -f ./CHANGELOG.rst ./docs/pages/changelog.rst
	poetry run doc8 -q docs

.DEFAULT:
	@cd docs && $(MAKE) $@

