---
logfile: /var/log/wtfo/dynaddrmgr.log
syslog: false
firewall_handler: ufw
dynamic_hosts_open_ports:
  - name: dynpr.wtforg.net
    ipv4: true
    ipv6: true
    ipv6net: 64
    ports:
      tcp:
        - 22
  - name: cosprings.teknofile.net
    ipv4: true
    ipv6: false
    ports:
      tcp:
        - 22
dynamic_host_templates:
  wtf-privy-static:
    src: /data/jim/development/ansible/wtf/infrastructure/files/dyntmpls/nginx-trusted-access.conf.j2
    dest: /tmp/access-wtf-trusted.conf
    owner: root
    group: sudo
    mode: "0640"
    hosts:
      - name: dynpr.wtforg.net
        ipv4: true
        ipv6: true
        ipv6net: 64
      - name: cosprings.teknofile.net
        ipv4: true
        ipv6: false
      - name: jimphone.mywire.org
        ipv4: true
        ipv6: true
        ipv6net: false
        prune: dynpr.wtforg.net
      - name: jimipad.mywire.org
        ipv4: true
        ipv6: true
        ipv6net: false
        prune: dynpr.wtforg.net
    backup: 5
    backup_dir: /tmp
    on_changed:
      - echo
      - systemctl reload nginx.service
  fail2ban-defaults:
    src: /data/jim/development/ansible/wtf/infrastructure/files/dyntmpls/00-defaults-vultr.conf.j2
    dest: /tmp/00-defaults.local
    owner: root
    group: sudo
    mode: "0640"
    hosts:
      - name: dynpr.wtforg.net
        ipv4: true
        ipv6: true
        ipv6net: 64
      - name: cosprings.teknofile.net
        ipv4: true
        ipv6: false
    backup: 5
    backup_dir: /tmp
    on_changed:
      - echo
      - systemctl reload fail2ban.service
...
